### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by failable** [applied-knowledge-systems/the-pattern-api#4]
I'm trying to follow [this post](https://metacortex.engineer/post/2021-08-07_bert-models-with-millisecond-inferencethe-pattern-project/), but I got the following error.

```
Traceback (most recent call last):
  File "app.py", line 62, in <module>
    from graphsearch.graph_search import *
  File "/Users/user/Downloads/the-pattern-api/graphsearch/graph_search.py", line 35, in <module>
    from utils import find_matches, loadAutomata
ModuleNotFoundError: No module named 'utils'
```

**Comment by AlexMikhalev** [comment]
Fixed

**Comment by AlexMikhalev** [comment]
I haven't noticed this issue for a while. 
You need a full pipeline:
```
git clone --recurse-submodules https://github.com/applied-knowledge-systems/the-pattern.git
cd the-pattern
bash ./bootstrap_benchmark.sh
```
if everything works you shall get the output of the curl command via API
```
curl -i -H “Content-Type: application/json” -X POST -d ‘{“search”:”Who performs viral transmission among adults?”}’ http://localhost:8080/qasearch
```
and time for PyTorch+hugginface of the shelf pipeline.
